services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: devinelazik
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 5s
      retries: 5

  next_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://example:example@postgres:5432/devinelazik"
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DEEZER_CLIENT_ID: "prout"
      DEEZER_CLIENT_SECRET: "caca"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data:
